verbose: True

run: results

exp: 
    - Chow_1
    - Nicol
    - vanGompel_1
    - Kush_Dillon_1
    - Kush_Dillon_2

lang: en

model_type: auto

models: 
        gpt2:
            - gpt2-xl
        tfxl:
            - transfo-xl-wt103

include_punct: False
